### ISSUE TITLE
Fixes checklist week 1

### ISSUE THREAD

**Issue by yonimor** [ghyonimor/rtblogapp#1]
- [x] File separation.
- [x] Code refactoring.
- [x] Active state on filters.
- [x] Lowercase URLs.
- [x] Fix 'Show x posts'.
- [x] Search should not submit form.
- [x] Show / hide pagination.
- [x] Disable filter on single post.
